# conda env create -f requirements.yml 
name: zoo_vision_env
channels:
- conda-forge
dependencies:
- python==3.12
- catkin_pkg
- scipy
- pandas
- matplotlib
- ipykernel
- ipython
- enlighten
- statsmodels